var firstName = 'Abirami Aravind';
console.log(firstName, typeof firstName);
var companyName = 'XYZ Corp';
console.log(companyName, typeof companyName);
var mobileNumber = 6789234567;
console.log(mobileNumber, typeof mobileNumber);
var isAutomation = true;
console.log(isAutomation, typeof isAutomation);
var hasAutomation;
console.log(hasAutomation, typeof hasAutomation);